### ISSUE TITLE
Change name from Prime7 to Seven Network

### ISSUE THREAD

**Issue by nextux** [adamrumbold/Channel7.bundle#2]
The correct name is Seven Network.  To many regional viewers, Prime7 would be correct, however the programming is sourced from Seven.

Also icon needs to be corrected as well.

![seven](https://f.cloud.github.com/assets/3284938/522674/774468dc-c05a-11e2-9c0b-aa1b86c32886.png)

**Comment by adamrumbold** [comment]
Changed icon - changed name and all references to Channel 7 (inline with Ch9/Ch10).
