### ISSUE TITLE
Audio stream plays but video doesn't.

### ISSUE THREAD

**Issue by JamieWritesCode** [adamrumbold/Channel7.bundle#3]
Hi, not sure if you're still actively developing this plugin but I've run into an issue.  I have downloaded the master .bundle and installed on PMS Windows 7 x64.  Playing with PMC on Win7 x64.  Show's load and display correctly but when I play an episode: I can hear the audio playing, however there is no video and PMS continues to display the loading image.

Logs here:
http://pastebin.com/izdz8gPD
http://pastebin.com/2qwDhpAf

Thanks in advance for any advice.  Unfortunately python is not my forte... :)

**Comment by adamrumbold** [comment]
I've just updated the site config as the flash player URL had changed.  Seem to be playing OK my end now.  

Can you please update and let me know how it goes. thanks

**Comment by JamieWritesCode** [comment]
Problem solved!  Thanks for your awesome work.
